### ISSUE TITLE
Support rust-analyzer or consider a pull request to rust-analyzer

### ISSUE THREAD

**Issue by JKAnderson409** [dustypomerleau/rust-syntax#1]
This extension is excellent and exactly what I have been looking for. I was disappointed to find that the easier-to-use and somewhat more feature-rich rust-analyzer extension is not supported. It seems to override this extension and they cannot work in tandem. My solution was to copy your "rust.tmLanguage.json" to the downloaded rust-analyzer folder and change the name to "rust.tmGrammar.json" after deleting their file by the same name. Because rust-analyzer uses its own syntax tree it did not seem to notice the difference. I now have the best of both worlds: good code analysis and perfect syntax highlighting.

Since it was so easy, it might be worth submitting this grammar to the actual repository for rust-analyzer since it is going to replace RLS as the official IDE language server. Presumably that extension will then be the official extension for Rust in VS Code. Otherwise it may help attract more users to just support the rust-analyzer extension with this one.

**Comment by dustypomerleau** [comment]
I have asked about this in [this post on the Rust Forum](https://users.rust-lang.org/t/are-you-happy-with-the-current-state-of-rust-syntax-highlighting/49399). My thoughts, based on recent experience + the feedback I received are:

- You're correct that Rust Analyzer is likely to surpass RLS in popularity.
- It may become possible to use the supported Rust extension with RA in the near future, which would work around the conflict, because the main Rust extension doesn't ship a grammar.
- There may be other workarounds, such as defining a new language name, and instructing users to change the `files.associations` portion of `settings.json` to use the new grammar. My initial attempts at doing that were... unsuccessful, but I haven't put a lot of time into it yet.
- Your plan to merge this extension with RA would be my personal preference, but the RA team is focused on semantic highlighting, and not interested in a PR for a new regex-based grammar.
- When the semantic highlighting bugs are worked out, there may be less need for extensions like this one, because most tokens on the page will be scoped by the semantic AST.
- Currently semantic highlighting in RA still has a lot of bugs. I am running into a lot of `unresolvedReference` scopes that shouldn't be there, so in the interim we are stuck with the choice of using the grammar with RLS, using the grammar that ships with RA, using a workaround (as you've done), or using semantic highlighting and dealing with the bugs (which I believe is currently the popular option).
- I am planning to update my Yarra Valley theme to better support semantic highlighting, but I haven't done so yet. 
- It's basically impossible to have the level of nuance that this grammar provides in conjunction with semantic highlighting. Many of the little eye-candy tweaks get steamrolled. So, in the end, most users will have to choose one or the other.

**Comment by dustypomerleau** [comment]
I have given this a bit more thought. Given there appears to be some early interest in this grammar, and given that Rust Analyzer is likely to be the future default, it is worth formally asking if the grammar can be merged while RA development is still at an earlier stage. I will mention this issue when I submit the PR so that you are notified to follow or participate in the discussion.

**Comment by jonasbb** [comment]
The embedded Rust grammar in VSCode is quite outdated. As far as I can tell they use https://github.com/zargony/atom-language-rust, which was last updated and has a bunch of open issues and pull-requests. Instead of up streaming the changes to rust-analyzer or maybe in addition they could also be included into VSCode. There also is an open issue against VSCode for better Rust support: https://github.com/microsoft/vscode/issues/64488

**Comment by dustypomerleau** [comment]
@jonasbb Thanks for tagging the VS Code issue. It looks like the core team may be willing to upstream the grammar in Rust Syntax rather than the Atom grammar. Hopefully a positive feedback loop will make it the ongoing default.

**Comment by dustypomerleau** [comment]
Looks like the merge of https://github.com/rust-analyzer/rust-analyzer/pull/6137 will close this. Thank you for your feedback,.
