### ISSUE TITLE
Macro metavariable.specifier with space between : parsed as variable

### ISSUE THREAD

**Issue by GrayJack** [dustypomerleau/rust-syntax#10]
I noticed that in macros syntax when the parameters are defined with a whitespace after  `:` it is not scoped as metavariable.specifier

To reproduce
```rust
macro_rules! my macro {
    ($a:tt $b: tt) => ()
}
```

**Image:** 
![image](https://user-images.githubusercontent.com/17973728/102839016-54d55580-43de-11eb-861e-ddfe6f7586e3.png)

The first `tt` is scoped as metavariable.specifier, while the second is not.

I'm using the lastest version that comes with rust-analyzer

**Comment by dustypomerleau** [comment]
You're correct, of course. This isn't the only pattern where I've relied on convention to keep the scope narrow and avoid edge cases. Since the unspaced version is what's shown in [The Rust Reference](https://doc.rust-lang.org/reference/macros.html), [The Little Book of Rust Macros](https://github.com/DanielKeep/tlborm), and all the codebases I've seen, that's how I've handled it.
