### ISSUE TITLE
rust grammar does not assign keyword scope to some keywords

### ISSUE THREAD

**Issue by alexr00** [dustypomerleau/rust-syntax#16]
From @a5hk  in https://github.com/microsoft/vscode/issues/120363

This issue is related to #108254 .  Can we have keyword scope too? Something like this:

```json
{
    "comment": "struct declarations",
    "match": "\\b(struct)\\s+([A-Z][A-Za-z0-9]*)\\b",
    "captures": {
        "1": {
            "name": "keyword.declaration.struct.rust storage.type.rust"
        },
        "2": {
            "name": "entity.name.type.struct.rust"
        }
    }
}
```
which results in:

![image](https://user-images.githubusercontent.com/5412540/113331136-cc4b4700-9334-11eb-8f5e-88b8337a9b13.png)

I used the scope from [https://www.sublimetext.com/docs/3/scope_naming.html#storage](url).

**Comment by dustypomerleau** [comment]
Hi, @a5hk, thanks for raising this. When I originally wrote the grammar, all of the terms in question had `keyword` scope. Based on feedback in the original issue, I was asked to bring them more in line with convention and change some to `storage`. Since many themes make no distinction between `keyword` and `storage`, I saw no harm in letting themes distinguish allocating keywords if they preferred. This was consistent with what some of VS Code's flagship languages were doing. For example, [TypeScript's `enum`](https://github.com/microsoft/vscode/blob/b2f203113c155f81a92fa5448b69b6170d16b2f7/extensions/typescript-basics/syntaxes/TypeScript.tmLanguage.json#L1882) was receiving only `storage.type.enum.ts`. 

Since the top of the scope stack will determine the highlighting, adding these scopes will not change the highlighting of any existing themes. It does allow more granular override of the highlight color for these keywords, either for theme designers or those that want to do so in `settings.json`. Is that your use case? If that is the use case, adding a more specific subset of `storage.type` is probably a cleaner way to accomplish this. So instead of changing `storage.type.rust` to `keyword.declaration.enum.rust storage.type.rust`, you would simply change it to `storage.type.enum.rust`. This gives the same level of targeting specificity without extra scopes in the stack.

**Comment by a5hk** [comment]
Yes, adding `keyword.declaration.enum.rust` like the way I suggested (originally from [Sublime Text](https://www.sublimetext.com/docs/scope_naming.html#storage)) won't change highlighting of existing themes. which is good and was intended. It will prevent breaking anything. But in my own themes I like use different colors for types and keywords. Example in Go:
![image](https://user-images.githubusercontent.com/5412540/120072684-505a4a80-c0aa-11eb-9c76-a2fc2f67641f.png)

> This was consistent with what some of VS Code's flagship languages were doing. For example, [TypeScript's `enum`](https://github.com/microsoft/vscode/blob/b2f203113c155f81a92fa5448b69b6170d16b2f7/extensions/typescript-basics/syntaxes/TypeScript.tmLanguage.json#L1882) was receiving only `storage.type.enum.ts`.

The [Sublime Text's approach](https://www.sublimetext.com/docs/scope_naming.html#storage) makes more sense to me.

With a keyword scope I can target all of those tokens simply with `keyword storage.type`, that's my use case. If anyone wants to be more specific and for example target declarations they are able to. A different color for struct and enum? it is possible. No language specific rules, so it should be easier to create more general themes (supporting more languages) this way. Also I think that `declaration` part makes it more compatible with semantic highlighting which has a declaration modifier.
